# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=dbg
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),dbg)
  lowflow_config = dbg

else ifeq ($(config),rel)
  lowflow_config = rel

else
  $(error "invalid configuration $(config)")
endif

PROJECTS := lowflow

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

lowflow:
ifneq (,$(lowflow_config))
	@echo "==== Building lowflow ($(lowflow_config)) ===="
	@${MAKE} --no-print-directory -C . -f lowflow.make config=$(lowflow_config)
endif

clean:
	@${MAKE} --no-print-directory -C . -f lowflow.make clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  dbg"
	@echo "  rel"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   lowflow"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"