#ifndef LF_COMPILER_LEXICAL_ANALYSIS
#define LF_COMPILER_LEXICAL_ANALYSIS

typedef enum LF_Token {
  LF_TOKEN_IDENTIFIER,
  LF_TOKEN_FUNC_CALL_NAME,
  LF_TOKEN_FUNC_CALL_BEGIN,
  LF_TOKEN_FUNC_CALL_END,
  LF_TOKEN_FUNC_CALL_ARG_NAME
} LF_Token;

#endif // LF_COMPILER_LEXICAL_ANALYSIS
